### ISSUE TITLE
Example/Possible Alternative Blink Recognition?

### ISSUE THREAD

**Issue by r-i-c-h** [jonaskuske/smoothscroll-anchor-polyfill#22]
I'd rather not add another library just to detect the Blink layout engine.

Possible alternative detection(s) of Blink?...
```javascript
if ( ((window.chrome || (window.Intl && Intl.v8BreakIterator)) &&
    'CSS' in window) ||
  /webkit\/537\.36.+chrome\/(?!27)/i.test(navigator.userAgent)
) {
  // Blink Engine
  window.__forceSmoothscrollAnchorPolyfill__ = true;
}
```

**Comment by jonaskuske** [comment]
Hey,

you're right that having to load another library to detect Blink is not optimal.

Unfortunately I haven't found another reliable way to detect the engine so far. One could probably remove everything that's not needed to detect Blink from `browsengine.js` to make it a least a little bit more lightweight, but that's out of scope for this package imo (and I don't have the time right now).

Your example evaluates to `true` in Microsoft Edge (v18, which is EdgeHTML not Blink), so probably needs a couple more checks 😞

Also, I'd rather not ship the detection as part of this package but leave it up to the user, for two reasons:
  - I suppose most users don't need it, smooth scroll while navigating the history is rather a niche requirement I think (happy to reconsider this though). I prefer defaulting to the native implementation where possible, especially as it prevents other unwanted side effects. (e.g. #20)
  - Heuristics for engine detection can be very brittle and frankly I don't want to be responsible for always keeping it up to date.

So if you really need smooth history navigation in Blink-based browsers, I unfortunately can't offer a better solution right now.
