### ISSUE TITLE
doesnt work in IE11

### ISSUE THREAD

**Issue by rocifier** [jonaskuske/smoothscroll-anchor-polyfill#29]
Tried the font-family hack and the inline style on <html>, IE11 just jumps to named anchors immediately.

**Comment by jonaskuske** [comment]
Did you load both
`<script src="//unpkg.com/smoothscroll-polyfill/dist/smoothscroll.min.js"></script>`
and
`<script src="//unpkg.com/smoothscroll-anchor-polyfill"></script>`
? :)

**Comment by rocifier** [comment]
Thanks for your prompt reply. I've just tried step 2a:

<script src="https://unpkg.com/smoothscroll-anchor-polyfill"></script>

I only require smooth scrolling for links to named anchors. Is there a pre-requisite of smoothscroll.min.js for that use case?

**Comment by jonaskuske** [comment]
> Is there a pre-requisite of smoothscroll.min.js for that use case?

Yep. Or not [`smoothscoll-polyfill`](https://github.com/iamdustan/smoothscroll) specifically, but rather any Polyfill that enables `window.scroll({ behavior: 'smooth' })` and `Element.scrollIntoView({ behavior: 'smooth' })`
– as `smoothscroll-anchor-polyfill` is using that under the hood, and is itself just concerned with detecting clicks on anchors, hashchanges, updating the URL and focus management. Dropping in

```html
<script src="//unpkg.com/smoothscroll-polyfill/dist/smoothscroll.min.js">
```
in addition to `smoothscroll-anchor-polyfill` is probably the easiest way to get started. :)

**Comment by jonaskuske** [comment]
Adding the above should fix your issue, if not feel free to comment again and I'll reopen :)
