### ISSUE TITLE
Bailout if defaultPrevented === true

### ISSUE THREAD

**Issue by jonaskuske** [jonaskuske/smoothscroll-anchor-polyfill#32]
```html
<a id="next" href="#">Next slide</a>
<script>
  document.querySelector('#next').addEventListener('click', e => e.preventDefault())
</script>
```

In browsers with native support, clicking the anchor from the example above does **not** scroll the page – `.preventDefault()` stops the default `href="#"` scroll behavior.

`smoothscroll-anchor-polyfill` currently ignores this, its clickHandler starts scrolling even if `event.defaultPrevented === true`. Needs fix.

**Comment by iamkeir** [comment]
Just encountered this too - is there a short-term workaround before it is officially fixed/released?

**Comment by jonaskuske** [comment]
@iamkeir Yep, change [line 264](https://github.com/jonaskuske/smoothscroll-anchor-polyfill/blob/master/index.js#L264)

from this:

```js
      if (evt.metaKey || evt.ctrlKey || evt.shiftKey || evt.button !== 0) return;
```
to this
```js
      if (evt.metaKey || evt.ctrlKey || evt.shiftKey || evt.button !== 0 || evt.defaultPrevented) return;
```

and you should be good :)

And I'll write a test for it and release the new version this week. 👍🏻

**Comment by jonaskuske** [comment]
@iamkeir Fixed and published :)

**Comment by iamkeir** [comment]
You’re the best!! Thank you for such a swift fix. Happy Easter.

**Comment by iamkeir** [comment]
I'm being a bit special... where can I download the new dist version?

**Comment by iamkeir** [comment]
Ah, got it:
https://unpkg.com/smoothscroll-polyfill/dist/smoothscroll.min.js
https://unpkg.com/smoothscroll-anchor-polyfill

**Comment by jonaskuske** [comment]
Yep! If you don't get the latest version, specify it explicitly with https://unpkg.com/smoothscroll-anchor-polyfill@1.3.2 – otherwise unpkg might still give you an older version due to caching. This way you also won't run into trouble if a v2 with breaking changes is published at some point.  
(I should also update the docs to recommend specifying the version as part of the URL)

**Comment by iamkeir** [comment]
Thanks dude - I also wondered why the dist folder was empty? Anyway all good, thank you very much :) Do you have a tip jar?

**Comment by jonaskuske** [comment]
> I also wondered why the dist folder was empty

The repository only contains the source code. When publishing the package to the npm registry, that source code is (more or less) automatically compiled into the [dist files](https://unpkg.com/browse/smoothscroll-anchor-polyfill@1.3.2/dist/) you can then use via unpkg and similar CDNs and registries. But they don't need to stay in the repo, the repo just includes the code and instructions necessary to predictably regenerate them.

And thanks, but nope, not looking for tips :)
