### ISSUE TITLE
Polyfill removes path from URL on anchor click

### ISSUE THREAD

**Issue by nick0** [jonaskuske/smoothscroll-anchor-polyfill#50]
Hello,

Thank you for sharing your awesome Smoothscroll Anchor Polyfill. It's fantastic, I'm really stoked on it and would love to use it moving forward.

In my testing it works really well in the "scroll-behavior:smooth challenged / problematic" Safari and IE = well done and thank you :)

I am using your polyfill on an (offline, development) Evolution CMS site and have a query relating to anchor link urls...

In the backend, an anchor link in the Evolution CMS might look like this (without the page alias in the link):
```
<li><a href="#anchor[+id+]">[+pagetitle+]</a></li>
or
<div><a href="#anchorTop"></a></div>

```

In the front end, the anchor links of these two items look like this (with the page alias put into the link so that same page anchor links work):
```
<li><a href="/page-1/#anchor121">My Page Name</a></li>
and
<div><a href="/page-1/#anchorTop"></a></div>
```

So the CMS adds the page alias into the anchor link . Ordinarily that's not a problem with an anchor link and you can scroll up and down a page without reloading the page.

But what seems to be happening when an anchor link is clicked with the Smoothscroll Anchor Polyfill active is that the page alias is removed from the anchor links and when clicking another anchor link on that page, the page actually reloads.

Eg This anchor link...
```
<div><a href="/page-1/#anchorTop"></a></div>
```
should have a url like...
```
mydomain.com/page-1/#anchorTop
```
but the page url actually becomes this when clicking that anchor link...
```
mydomain.com/#anchorTop
```
If I click another anchor link on that same page, the page reloads and the url becomes...
```
mydomain.com/page-1/#different-anchor
```
etc

So I am in some sort of weird loop with the url changeing and the page reloading with the Smoothscroll Anchor Polyfill active.
eg
```
clicking an anchor link with the following url
	mydomain.com/page-1/#anchorTop
scrolls to the anchor with page alias removed
	mydomain.com/#anchorTop
clicking another anchor on that same page results in a page reload before going to that new anchor
	mydomain.com/#page-1/my-different-anchor
clicking a different anchor link on that same page scrolls to the anchor with page alias removed
	mydomain.com/#my-other-anchor
etc and now I am dizzy :)
```

If I remove the two Smoothscroll Anchor Polyfill javascripts from the page, this issue no longer happens - I can smooth scroll up and down a page as expected and as many times as I like and the page is never reloaded (but obviously I would not get the great benefits of your Polyfill with Safari and IE).

Have you got any tricks to stop your Polyfill script from removing the page alias from clicked anchor links?
(I am not a programmer so please go easy on me with any code ;) )

Many thanks in advance.

**Comment by jonaskuske** [comment]
Thanks for your detailed report! I'll investigate :)

**Comment by nick0** [comment]
Thanks so much.
Good call on the title change :)
If you would like CMS login access to a demo page so you can see the issue in action, please sing out, wouldn't take long to set up.
Cheers.

**Comment by jonaskuske** [comment]
Could you let me know in which browser you're seeing this issue?
And yep, a demo page or some kind of repro would be super helpful as I couldn't reproduce the issue in my testing. (the path was preserved and just the hash changed, as intended)

**Comment by nick0** [comment]
Sure thing... Firefox 94.0.1 (64-bit)

Roger that, just setting the demo page up now. Not sure how to do repro / what a repro is sorry, but can give you demo CMS access.

Sorry if this is a dumb question... how do I contact you privately to send demo access?

Thanks.

**Comment by nick0** [comment]
Maybe try this as a live page on the test site (will delete and make offline once you've seen it)...

Click the links in the LHS vertical menu to scroll up and down and compare the two pages.

(links x 2 removed)

(anchor links made manually - the same issue happens as with menu generated links. Likely because Evolution inserts the page path and your script seems to remove it?)

Interested to hear your thoughts.

If you need CMS access for code play etc, please sing out and advise private way to send you access (eg an email address).

Thanks again,

**Comment by jonaskuske** [comment]
Thanks!
Found the culprit: your site uses a base element with `<base href="https://gocreated.com.au/">`, so when the polyfill adds `#anchor`, it isn't appended to the *current* URL as usual, but to the base one instead, which gives you `https://gocreated.com.au/#anchor`, removing any path in between.

I've already implemented a fix – still need to test it, to verify it doesn't cause issues for others, but should be live by the end of the day! :)

**Comment by jonaskuske** [comment]
Alright, v1.3.4 is published – give it a go! :)

(you can append the version to the package name in your script: `<script src="https://unpkg.com/smoothscroll-anchor-polyfill@1.3.4">`)

**Comment by nick0** [comment]
Thank you so much. That works perfectly!

Just tested in 5 browsers and 3 different test sites and the anchors now scroll consistently up and down the page, even when using the "non version" package name for the latest scripts like so;
```
<script src="https://unpkg.com/smoothscroll-polyfill/dist/smoothscroll.min.js"></script>
<script src="https://unpkg.com/smoothscroll-anchor-polyfill"></script>
```

Thank you kindly, that is brilliant - truly love your work :)
