### ISSUE TITLE
Support scroll-margin

### ISSUE THREAD

**Issue by macakronos** [jonaskuske/smoothscroll-anchor-polyfill#51]
I can think of it to be with a css variable. 

Currently scroll-margin. It doesn't work in Safari, so to solve that need I came up with that option. Thank you for your contribution to the community.

**Comment by jonaskuske** [comment]
Same situation as https://github.com/jonaskuske/smoothscroll-anchor-polyfill/issues/34#issuecomment-1040776709 :)
(though I must say I'll look into `scroll-padding` first as I think it's more common, mostly for fixed headers)

**Comment by jonaskuske** [comment]
Good news, found out that `scroll-margin` support is implemented by https://github.com/magic-akari/seamless-scroll-polyfill, a more modern (and larger) fork of https://github.com/iamdustan/smoothscroll.

So if you use that in tandem with `smoothscroll-anchor-polyfill`, scroll-margin is supported. For example:

```html
<script src="https://unpkg.com/seamless-scroll-polyfill@2.1.8/lib/bundle.min.cjs"></script>
<script src="https://unpkg.com/smoothscroll-anchor-polyfill@1.3.4/dist/index.min.js"></script>
<script>
// enable seamless-scroll-polyfill
seamless.polyfill()
</script>
```

Note that in Safari < 14.5 `scroll-margin` is called `scroll-snap-margin`, so if you support older Safari versions you'll need to add that property as well.

**Comment by macakronos** [comment]
Excellent. Thanks jonaskuske.
